### ISSUE TITLE
Web Client Enhancement

### ISSUE THREAD

**Issue by kfitfk** [mssjappjwt/PDSite#5]
Need a place to keep track of the modifications.

- [x] 1. Take profile picture and blur it in the background of the header with 0.4 alpha black overlay
- [x] 2. Increase scroll height (last post at the bottom gets cut off my fixed player)
- [x] 3. Activate like button + subreply/subreply count —> Download App Popup
- [x] 4. Scrubbing sound waves
- ~~5. Click sound waves to play audio~~

1. I don't get it. An image will help :)
2. Missing `padding-bottom`, easy fix
3. I guess it's better to make like button an independent component. Is API for like ready? What happens when I click reply button next to the like button?
4. Is it only the waves? Or the timeline of fixed player also responds to mouse events?

**Comment by innovation96** [comment]
I just pushed the latest set of changes. 

**I don't get it. An image will help :)**
Take a look at [this screenshot](https://cloud.githubusercontent.com/assets/18356769/14609909/c269a4ca-0559-11e6-8f90-3289a913bb0e.png)
This is already configured on a basic level in  main.css

**Missing padding-bottom, easy fix **
Great!

**I guess it's better to make like button an independent component. Is API for like ready? What happens when I click reply button next to the like button?**
Jason will provide the API for like + sub-reply count. However, since there is no user authentication layer on the web client, clicking like or reply will simply toggle a pop-up to input your phone number to receive the app link.

**Is it only the waves? Or the timeline of fixed player also responds to mouse events?**
BOTH the fixed player's timeline AND the soundwaves in each post should respond to mouse events.

**Sub-reply interface**
Sub-replies are messed up currently. They need to be realigned!

**Comment by kfitfk** [comment]
**Take profile picture and blur it in the background of the header with 0.4 alpha black overlay**
Got it. CSS filter with a pseudo element will do.

**Activate like button + subreply/subreply count —> Download App Popup**
So for now both buttons act the same. A pop-up shows when click either one.

**Scrubbing sound waves**
Wavesurfer is a third party library, which may make it a little complicated. I'll update after I try.

**Comment by kfitfk** [comment]
I pushed to the branch - enhance-player. 

Now the blurred profile picture is showing and clicking subreply and like buttons show a modal view.

However, Chrome shows some weird white soft edges around the blurred image, Firefox and Safari doesn't with my current CSS. Please tweak the numbers and try to find the balance.

I don't know what to put in the modal view, I'll leave that to you.

**Comment by innovation96** [comment]
Looking great! Here's a final list of improvements and we'll be all set for now 👍 

**SUB-REPLIES** ([this talk](http://localhost:7780/#/talks/56d63a43536e261a00364dde?_k=ppcjxe) (talk_id = 56d63a43536e261a00364dde) has a reply with > 1 subreply. Use it for reference in your development)
- [ ] Hide reply and like buttons
- [ ] Add left indentation line
- [ ] Reduce waveform width and bring back play button
- [ ] Reduce subreply avatar size to 30px by 30px
- [ ] Collapse all subreplies after the first (collapsed state [here](https://cloud.githubusercontent.com/assets/18356769/14657281/df2c2856-065a-11e6-9a0f-d7b6bbbef849.png), expanded state [here](https://cloud.githubusercontent.com/assets/18356769/14657297/eda79c94-065a-11e6-91e0-a6c97fdfcf49.png))


**DOWNLOAD MODAL** - **I designed it for you** [**here**](https://cloud.githubusercontent.com/assets/18356769/14657547/96d04b1c-065c-11e6-9c54-c9f241a3afbd.png)
- [ ] Phone number input, Send App Link Button, Close Button, Text (no back-end config for now)


**REPLY MODAL** (no back-end config necessary yet) - toggle this when clicking 'Reply to [username]' button (**design** [**here**](https://cloud.githubusercontent.com/assets/18356769/14657608/f07476f2-065c-11e6-9940-5f7e6b00c2ca.png)) 
- [ ] Optional nickname input 
- [ ] Comment/question input 
- [ ] Character count (max 100 characters)
- [ ] Send button (0.5 alpha by default, 1.0 alpha as soon as comment/question text is detected) 


**OTHER FIXES**
- [ ] If user has no profile picture, use [**this default avatar**](https://cloud.githubusercontent.com/assets/18356769/14657327/31c1fef6-065b-11e6-9c97-c79409ea7a55.png).
- [ ] All soundwaves should be bottom aligned, not center aligned, like [this](https://cloud.githubusercontent.com/assets/18356769/14657369/83fe3b9e-065b-11e6-801e-1dfcc3ed06d4.png).
- [ ] Scrubbing soundwaves (save this for the very end, it's the least crucial)

**Comment by kfitfk** [comment]
Done most of the sub-replies related modifications. I've added the view more replies button, which is yet to be tested. Because something is very wrong with my VPN tonight. I can barely open the page to test and update the styles. @mssjappjwt need help with the style.

**Comment by innovation96** [comment]
You probably were not able to run the client because of your VPN issue, but all replies are now completely hidden from view. Do you think you can fix this before continuing to the other changes? Thanks so much :)
<img width="1280" alt="screen shot 2016-04-20 at 3 31 20 pm" src="https://cloud.githubusercontent.com/assets/18356769/14687704/f354a472-070c-11e6-9b05-b0a28408935c.png">

**Comment by kfitfk** [comment]
Oops. Sorry I didn't notice that. It's fixed.

**Comment by innovation96** [comment]
Hmm, I still can't see the replies. I'm running the latest version, too. Can you take another look? Thanks!

**Comment by innovation96** [comment]
Not seeing the default profile pic render yet. Otherwise, fantastic job! You've been a tremendous help so far.

**Comment by kfitfk** [comment]
Currently I use the default profile pic for the blurred banner if no user profile pic returned from server. Do I miss anything here?

**Comment by innovation96** [comment]
That default prpfile pic should show up for the actual user avatar in the post, too:

<img width="536" alt="screen shot 2016-04-22 at 1 02 01 pm" src="https://cloud.githubusercontent.com/assets/18356769/14748918/6fbd9608-088a-11e6-9b57-548b1c242274.png">

**Comment by innovation96** [comment]
The Twitter card waveform looks a lot nicer than the web client. 

@mssjappjwt said you customized the waveform for the Twitter card, but used a 3rd party library for the web client waveforms. Can you remove the 3rd party library from the web client and replace it with the customized waveform code you made for the Twitter card?

It would also be great if you could normalize the soundwaves so there isn't such a big fluctuation in the waveform height.

**Comment by kfitfk** [comment]
@innovation96 Actually they're the same library with almost the same settings. The difference is the settings for the wave's height. I guess the half height overlay caused some visual illusions.
![overlay](https://cloud.githubusercontent.com/assets/2555626/14803684/793c29f4-0b8e-11e6-9dc0-b237f69ceba5.jpg)

**Comment by innovation96** [comment]
I re-centered them for now - don't worry about it!
